services:
  # Web application
  web:
    container_name: lumina-web
    build: 
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG= True
    depends_on:
      - db

  # Database
  db:
    image: postgres:latest
    container_name: lumina-db
    environment:
      POSTGRES_DB: lumina_db
      POSTGRES_USER: lumina_user
      POSTGRES_PASSWORD: lumina_password
    volumes:
      - lumina_db_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  # Streamlit Dashboard
  streamlit:
    container_name: lumina-streamlit
    build: 
      context: .
      dockerfile: Dockerfile
    command: streamlit run src/dashboard/app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    depends_on:
      - db


volumes:
  lumina_db_data:


