[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](./LICENSE)
[![GitHub contributors](https://img.shields.io/github/contributors/unb-mds/2024-2-Squad05)](https://img.shields.io/github/contributors/unb-mds/2024-2-Squad05)
![]((https://img.shields.io/github/issues/unb-mds/2024-2-Squad05))
![](https://img.shields.io/github/issues-closed/unb-mds/2024-2-Squad05.svg)

## Lumina Análise de Sentimentos - 2024.2 - Squad 05

## 🔎 Sobre o Projeto: 

O **Projeto Lumina** tem como objetivo principal realizar a **Análise de Sentimentos** dos **Planos Participativos** disponibilizados pela maior plataforma de contribuição social do governo federal: o **Brasil Participativo**. 

## Objetivo Geral
Oferecer uma compreensão clara e acessível das percepções populares sobre as propostas enviadas pela sociedade, utilizando análise de sentimentos para identificar opiniões positivas, negativas e neutras.

## Objetivos Específicos
- Responder à crescente demanda por uma compreensão mais profunda das necessidades da população em áreas como **Sustentabilidade**, **Cultura** e **Direitos Humanos**.
- Fornecer dados que possam guiar as ações do governo federal, promovendo políticas públicas mais alinhadas com as demandas sociais.
- Facilitar o acesso a informações confiáveis e transparentes para cidadãos, pesquisadores e formuladores de políticas.

## Justificativa

O **Projeto Lumina** surge como uma resposta à necessidade crescente de compreender as percepções populares sobre políticas públicas e prioridades sociais. A plataforma **Brasil Participativo**, sendo a maior ferramenta de contribuição cidadã do governo federal, reúne um volume significativo de dados e comentários que expressam as demandas, opiniões e sentimentos da sociedade em relação a propostas de diversas áreas.

Embora os dados sejam ricos em informações, sua complexidade e volume dificultam a análise e a utilização eficiente por gestores, pesquisadores e cidadãos. Nesse contexto, a aplicação de **Análise de Sentimentos** se torna essencial, permitindo extrair insights valiosos de forma estruturada e acessível. 

Ao disponibilizar resultados claros e confiáveis, o Projeto Lumina não apenas facilita a tomada de decisões informadas, mas também promove a **transparência** e o **engajamento social**, contribuindo para uma gestão pública mais alinhada com as necessidades reais da população. Assim, o projeto reforça a importância de dados como base para uma governança participativa, inclusiva e responsável.


## 👥 Desenvolvedores
<center>
<table style="margin-left: auto; margin-right: auto;">
    <tr>
        <td align="center">
            <a href="https://github.com/arthurfernandesj">
                <img style="border-radius: 50%;" src="https://avatars.githubusercontent.com/u/90862900?v=4" width="150px;"/>
                <h5 class="text-center">Arthur Fernandes</h5>
            </a>
        </td>
        <td align="center">
            <a href="https://github.com/CaioPacheco">
                <img style="border-radius: 50%;" src="https://avatars.githubusercontent.com/u/90219652?v=4" width="150px;"/>
                <h5 class="text-center">Caio Pacheco</h5>
            </a>
        </td>
        <td align="center">
            <a href="https://github.com/GabrielSPinto">
                <img style="border-radius: 50%;" src="https://avatars.githubusercontent.com/u/144184007?v=4" width="150px;"/>
                <h5 class="text-center">Gabriel Santos</h5>
            </a>
        </td>
        </td>
        <td align="center">
            <a href="https://github.com/felixlaryssa">
                <img style="border-radius: 50%;" src="https://avatars.githubusercontent.com/u/143897458?v=4" width="150px;"/>
                <h5 class="text-center">Laryssa Felix</h5>
            </a>
        </td>
        <td align="center">
            <a href="https://github.com/luizh-gsoares">
                <img style="border-radius: 50%;" src="https://avatars.githubusercontent.com/u/99836497?v=4" width="150px;"/>
                <h5 class="text-center">Luiz Henrique</h5>
            </a>
        </td>
          <td align="center">
            <a href="https://github.com/LeticiaMonteiroo">
                <img style="border-radius: 50%;" src="https://avatars.githubusercontent.com/u/152661076?v=4" width="150px;"/>
                <h5 class="text-center">Letícia Monteiro</h5>
            </a>
        </td>
</table>
</center>

## 💻 Frameworks
- 📋 **Backlog do projeto:** [Clique aqui](https://unb-mds.github.io/2024-2-Squad05/documentation/productbacklog/)
- 🎨 **Prototipação:**  [Clique aqui](https://unb-mds.github.io/2024-2-Squad05/prototipo/prototipo/)
- 🏛️ **Arquitetura:** [Clique aqui](https://unb-mds.github.io/2024-2-Squad05/architecture/architecture/)
- 🌳 **Configuração do Ambiente:** [Clique aqui](https://unb-mds.github.io/2024-2-Squad05/configuracao/configuracao/)
- 🙋 **Como contribuir:** [Clique aqui](https://unb-mds.github.io/2024-2-Squad05/politicas/contribuicao/)

## 🗃️ Documentação
Para acessar a página web da nossa documentação [Clique aqui](https://unb-mds.github.io/2024-2-Squad05/)

### 📲 Demais configurações
- 📋 **Pré-requisitos:** [Clique aqui](https://unb-mds.github.io/2024-2-Squad05/configuracao/configuracao/#pre-requisitos)
- 💻 **Ambiente:** [Clique aqui](https://unb-mds.github.io/2024-2-Squad05/configuracao/configuracao/#ambiente-local)
- ⚙️ **Configuração e Execução:** [Clique aqui](https://unb-mds.github.io/2024-2-Squad05/configuracao/configuracao/#configuracao-e-execucao)

---
Lumina é um software livre, disponível sob a licença MIT.
